version: 2.1
jobs:
 build :
   docker : 
     - image: circleci/ubuntu-2004:202010-01
   steps :
    #- checkout
    # run : docker build -t app:latest .
   - run: echo "App started"
    
  
    
  
       
